# Generated by Django 5.0.6 on 2024-05-08 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("telegram_id", models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True, verbose_name="Ник в телеграм")),
                ("full_name", models.CharField(blank=True, max_length=255, null=True, verbose_name="Имя-Фамилия")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(max_length=500)),
                ("reminder_date_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("parsed", "Ожидание"), ("sent", "Отправлено"), ("failed", "Ошибка")],
                        default="parsed",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="reminder_bot_admin.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Напоминание",
                "verbose_name_plural": "Напоминания",
            },
        ),
    ]
